
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Workspace
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed class DataWorkspace : global::Microsoft.LightSwitch.Framework.Base.DataWorkspace<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of a DataWorkspace.  Changes can be made to data sources in the new instance independent of changes made to data sources in the default DataWorkspace.
        /// </summary>
        public DataWorkspace() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the ApplicationData datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ApplicationDataService ApplicationData
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData);
            }
        }
        
        /// <summary>
        /// Gets the NetworkData datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.NetworkDataService NetworkData
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.NetworkData);
            }
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ApplicationDataService> ApplicationData
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ApplicationDataService>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.NetworkDataService> NetworkData
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.NetworkData) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.NetworkDataService>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ApplicationDataService>.Entry
                    ApplicationData = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ApplicationDataService>.Entry(
                        "ApplicationData",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._ApplicationData_Stub);
                private static void _ApplicationData_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ApplicationDataService>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._ApplicationData, sf);
                }
                 
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.NetworkDataService>.Entry
                    NetworkData = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.NetworkDataService>.Entry(
                        "NetworkData",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._NetworkData_Stub);
                private static void _NetworkData_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.NetworkDataService>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._NetworkData, sf);
                }
                 
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ApplicationDataService>.Data _ApplicationData;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.NetworkDataService>.Data _NetworkData;
            
        }
    
        #endregion
    }
    
    #endregion
    
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the ApplicationData datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationData : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// This constructor is used for the internal LightSwitch framework. Use DataWorkspace instead.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ApplicationData() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.ApplicationData.DetailsClass.PropertySet, global::LightSwitchApplication.ApplicationData.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.ApplicationData.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ApplicationData.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
            }
    
        }
    
        #endregion
    }
    
    /// <summary>
    /// Provides members to query and update data in the NetworkData datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class NetworkData : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// This constructor is used for the internal LightSwitch framework. Use DataWorkspace instead.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public NetworkData() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the Networks entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Network> Networks
        {
            get
            {
                return global::LightSwitchApplication.NetworkData.DetailsClass.GetValue(this, global::LightSwitchApplication.NetworkData.DetailsClass.PropertySetProperties.Networks);
            }
        }
        
        /// <summary>
        /// Gets the Practices entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Practice> Practices
        {
            get
            {
                return global::LightSwitchApplication.NetworkData.DetailsClass.GetValue(this, global::LightSwitchApplication.NetworkData.DetailsClass.PropertySetProperties.Practices);
            }
        }
        
        /// <summary>
        /// Gets the Providers entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Provider> Providers
        {
            get
            {
                return global::LightSwitchApplication.NetworkData.DetailsClass.GetValue(this, global::LightSwitchApplication.NetworkData.DetailsClass.PropertySetProperties.Providers);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        /// <param name="Name">
        /// The value of the 'Name' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Network Networks_Single(global::System.Nullable<int> Id, string Name)
        {
            return this.Details.Methods.Networks_Single.CreateInvocation(Id, Name).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        /// <param name="Name">
        /// The value of the 'Name' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Network Networks_SingleOrDefault(global::System.Nullable<int> Id, string Name)
        {
            return this.Details.Methods.Networks_SingleOrDefault.CreateInvocation(Id, Name).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        /// <param name="Name">
        /// The value of the 'Name' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Practice Practices_Single(global::System.Nullable<int> Id, string Name)
        {
            return this.Details.Methods.Practices_Single.CreateInvocation(Id, Name).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        /// <param name="Name">
        /// The value of the 'Name' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Practice Practices_SingleOrDefault(global::System.Nullable<int> Id, string Name)
        {
            return this.Details.Methods.Practices_SingleOrDefault.CreateInvocation(Id, Name).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        /// <param name="FullName">
        /// The value of the 'FullName' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Provider Providers_Single(global::System.Nullable<int> Id, string FullName)
        {
            return this.Details.Methods.Providers_Single.CreateInvocation(Id, FullName).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        /// <param name="FullName">
        /// The value of the 'FullName' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Provider Providers_SingleOrDefault(global::System.Nullable<int> Id, string FullName)
        {
            return this.Details.Methods.Providers_SingleOrDefault.CreateInvocation(Id, FullName).Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.NetworkData.DetailsClass.PropertySet, global::LightSwitchApplication.NetworkData.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.NetworkData.DetailsClass.MethodSetProperties.Networks_Single;
                var initializePropertyEntry = global::LightSwitchApplication.NetworkData.DetailsClass.PropertySetProperties.Networks;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.NetworkData.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.NetworkData.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Network> Networks_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.NetworkData.DetailsClass.MethodSetProperties.Networks_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Network>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Network> Networks_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.NetworkData.DetailsClass.MethodSetProperties.Networks_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Network>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Practice> Practices_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.NetworkData.DetailsClass.MethodSetProperties.Practices_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Practice>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Practice> Practices_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.NetworkData.DetailsClass.MethodSetProperties.Practices_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Practice>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Provider> Providers_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.NetworkData.DetailsClass.MethodSetProperties.Providers_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Provider>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Provider> Providers_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.NetworkData.DetailsClass.MethodSetProperties.Providers_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Provider>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Network> Networks
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.NetworkData.DetailsClass.PropertySetProperties.Networks) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Network>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Practice> Practices
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.NetworkData.DetailsClass.PropertySetProperties.Practices) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Practice>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Provider> Providers
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.NetworkData.DetailsClass.PropertySetProperties.Providers) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Provider>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Network>.Entry
                    Networks_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Network>.Entry(
                        "Networks_Single",
                        global::LightSwitchApplication.NetworkData.DetailsClass.MethodSetProperties._Networks_Single_Stub);
                private static void _Networks_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NetworkData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Network>.Data> c, global::LightSwitchApplication.NetworkData.DetailsClass d, object sf)
                {
                    c(d, ref d._Networks_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Network>.Entry
                    Networks_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Network>.Entry(
                        "Networks_SingleOrDefault",
                        global::LightSwitchApplication.NetworkData.DetailsClass.MethodSetProperties._Networks_SingleOrDefault_Stub);
                private static void _Networks_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NetworkData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Network>.Data> c, global::LightSwitchApplication.NetworkData.DetailsClass d, object sf)
                {
                    c(d, ref d._Networks_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Practice>.Entry
                    Practices_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Practice>.Entry(
                        "Practices_Single",
                        global::LightSwitchApplication.NetworkData.DetailsClass.MethodSetProperties._Practices_Single_Stub);
                private static void _Practices_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NetworkData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Practice>.Data> c, global::LightSwitchApplication.NetworkData.DetailsClass d, object sf)
                {
                    c(d, ref d._Practices_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Practice>.Entry
                    Practices_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Practice>.Entry(
                        "Practices_SingleOrDefault",
                        global::LightSwitchApplication.NetworkData.DetailsClass.MethodSetProperties._Practices_SingleOrDefault_Stub);
                private static void _Practices_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NetworkData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Practice>.Data> c, global::LightSwitchApplication.NetworkData.DetailsClass d, object sf)
                {
                    c(d, ref d._Practices_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Provider>.Entry
                    Providers_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Provider>.Entry(
                        "Providers_Single",
                        global::LightSwitchApplication.NetworkData.DetailsClass.MethodSetProperties._Providers_Single_Stub);
                private static void _Providers_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NetworkData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Provider>.Data> c, global::LightSwitchApplication.NetworkData.DetailsClass d, object sf)
                {
                    c(d, ref d._Providers_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Provider>.Entry
                    Providers_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Provider>.Entry(
                        "Providers_SingleOrDefault",
                        global::LightSwitchApplication.NetworkData.DetailsClass.MethodSetProperties._Providers_SingleOrDefault_Stub);
                private static void _Providers_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NetworkData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Provider>.Data> c, global::LightSwitchApplication.NetworkData.DetailsClass d, object sf)
                {
                    c(d, ref d._Providers_SingleOrDefault, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Network>.Entry
                    Networks = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Network>.Entry(
                        "Networks",
                        global::LightSwitchApplication.NetworkData.DetailsClass.PropertySetProperties._Networks_Stub);
                private static void _Networks_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NetworkData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Network>.Data> c, global::LightSwitchApplication.NetworkData.DetailsClass d, object sf)
                {
                    c(d, ref d._Networks, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Practice>.Entry
                    Practices = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Practice>.Entry(
                        "Practices",
                        global::LightSwitchApplication.NetworkData.DetailsClass.PropertySetProperties._Practices_Stub);
                private static void _Practices_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NetworkData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Practice>.Data> c, global::LightSwitchApplication.NetworkData.DetailsClass d, object sf)
                {
                    c(d, ref d._Practices, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Provider>.Entry
                    Providers = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Provider>.Entry(
                        "Providers",
                        global::LightSwitchApplication.NetworkData.DetailsClass.PropertySetProperties._Providers_Stub);
                private static void _Providers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NetworkData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Provider>.Data> c, global::LightSwitchApplication.NetworkData.DetailsClass d, object sf)
                {
                    c(d, ref d._Providers, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Network>.Data _Networks;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Practice>.Data _Practices;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Provider>.Data _Providers;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Network>.Data _Networks_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Network>.Data _Networks_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Practice>.Data _Practices_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Practice>.Data _Practices_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Provider>.Data _Providers_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NetworkData, global::LightSwitchApplication.NetworkData.DetailsClass, global::LightSwitchApplication.Provider>.Data _Providers_SingleOrDefault;
            
        }
    
        #endregion
    }
    
    #endregion
    
}
